Repository wJoenn/rentart, pull requests merged in 2023-02, with the labels that each got.

#17 Cloudinary setup
  Gemfile
  Gemfile.lock
  config/environments/development.rb
  config/storage.yml
  db/migrate/20230216074529_create_active_storage_tables.active_storage.rb
Labels: waiting for review

#16 Some additional custom rules and css propreties for the project
  .rubocop.yml
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/config/_colors.scss
  app/assets/stylesheets/config/_fonts.scss
  app/assets/stylesheets/config/_setup.scss
Labels: waiting for review

#30 user auth implemented to Application controller
  app/controllers/application_controller.rb
  app/controllers/pages_controller.rb
Labels: waiting for review

#28 Art model branch
  Gemfile.lock
  app/controllers/arts_controller.rb
  app/models/art.rb
  app/views/arts/index.html.erb
  app/views/arts/new.html.erb
  app/views/arts/show.html.erb
  config/routes.rb
  db/migrate/20230215131812_create_arts.rb
  test/controllers/arts_controller_test.rb
  test/models/art_test.rb
Labels: waiting for review

#34 Generated devise views and updated some to form_with
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/devise/index.scss
  app/assets/stylesheets/devise/registrations/_edit.scss
  app/views/devise/confirmations/new.html.erb
  app/views/devise/mailer/confirmation_instructions.html.erb
  app/views/devise/mailer/email_changed.html.erb
  app/views/devise/mailer/password_change.html.erb
  app/views/devise/mailer/reset_password_instructions.html.erb
  app/views/devise/mailer/unlock_instructions.html.erb
  app/views/devise/passwords/edit.html.erb
  app/views/devise/passwords/new.html.erb
  app/views/devise/registrations/_form.html.erb
  app/views/devise/registrations/edit.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/devise/shared/_error_messages.html.erb
  app/views/devise/shared/_flashes.html.erb
  app/views/devise/shared/_links.html.erb
  app/views/devise/unlocks/new.html.erb
  app/views/layouts/application.html.erb
Labels: waiting for review

#4 navbar basic layout
  Gemfile.lock
  app/assets/images/artify_logo.png
  app/assets/images/avatar.png
  app/assets/stylesheets/components/_index.scss
  app/assets/stylesheets/components/_navbar.scss
  app/views/layouts/application.html.erb
  app/views/pages/home.html.erb
  app/views/shared/_form.html.erb
  app/views/shared/_navbar.html.erb
Labels: waiting for review

#36 A compatibility patch for User and Art model
  app/controllers/arts_controller.rb
  app/models/art.rb
  app/models/user.rb
  db/migrate/20230216075533_create_arts.rb
  db/schema.rb
Labels: bug, waiting for review

#43 bug fixed
  Gemfile.lock
  app/views/shared/_navbar.html.erb
  db/schema.rb
Labels: bug, waiting for review

#42 art validations fix
  app/models/art.rb
Labels: waiting for review

#38 Category model
  app/models/art.rb
  app/models/category.rb
  db/migrate/20230217191345_create_categories.rb
  db/migrate/20230217193124_add_category_to_arts.rb
  db/schema.rb
  test/models/category_test.rb
Labels: waiting for review

#33 Created form css component
  app/assets/stylesheets/components/_form.scss
  app/assets/stylesheets/components/_index.scss
Labels: waiting for review

#46 Added file extension to image_tag file path
  app/views/shared/_navbar.html.erb
Labels: bug

#32 Created button css component
  app/assets/stylesheets/components/_button.scss
  app/assets/stylesheets/components/_index.scss
Labels: waiting for review

#45 Created a seed file
  Gemfile
  Gemfile.lock
  app/models/art.rb
  db/seeds.rb
Labels: waiting for review

#47 application.html.erb and _setup.scss patch
  app/assets/stylesheets/config/_setup.scss
  app/views/layouts/application.html.erb
Labels: waiting for review

#51 Form navbar patch
  app/assets/stylesheets/components/_form.scss
  app/assets/stylesheets/components/_navbar.scss
  app/assets/stylesheets/config/_setup.scss
  app/views/shared/_form.html.erb
  app/views/shared/_navbar.html.erb
Labels: waiting for review

#52 Home page patch
  app/assets/stylesheets/components/_button.scss
  app/assets/stylesheets/components/_buttons.scss
  app/assets/stylesheets/components/_index.scss
  app/assets/stylesheets/config/_fonts.scss
  app/assets/stylesheets/pages/_home.scss
  app/views/devise/registrations/_form.html.erb
  app/views/pages/home.html.erb
Labels: waiting for review

#57 Form updates
  app/assets/stylesheets/components/_form.scss
  app/assets/stylesheets/config/_setup.scss
  app/views/devise/registrations/_form.html.erb
  app/views/devise/sessions/new.html.erb
Labels: waiting for review

#55 a- decoration none, color inherit
  app/assets/stylesheets/config/_setup.scss
Labels: requires changes

#54 fixed the link_to in the application folder and created the basic foo…
  app/assets/stylesheets/components/_footer.scss
  app/assets/stylesheets/components/_index.scss
  app/views/layouts/application.html.erb
  app/views/shared/_footer.html.erb
  app/views/shared/_navbar.html.erb
  db/schema.rb
Labels: waiting for review

#59 Form frontend preparation before javascript
  app/assets/stylesheets/components/_container.scss
  app/assets/stylesheets/components/_form.scss
  app/assets/stylesheets/components/_index.scss
  app/assets/stylesheets/config/_setup.scss
  app/views/devise/passwords/new.html.erb
  app/views/devise/registrations/edit.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/devise/shared/_flashes.html.erb
  app/views/devise/shared/_links.html.erb
  app/views/layouts/application.html.erb
  app/views/pages/home.html.erb
Labels: waiting for review

#63 Some Layout changes
  app/assets/images/artify_logo.png
  app/assets/images/avatar.png
  app/assets/images/logo_gold.png
  app/assets/images/logo_grey.png
  app/assets/images/mona_lisa.jpg
  app/assets/images/sign_up.png
  app/assets/stylesheets/components/_footer.scss
  app/assets/stylesheets/components/_form.scss
  app/assets/stylesheets/components/_navbar.scss
  app/assets/stylesheets/config/_setup.scss
  app/views/shared/_footer.html.erb
  app/views/shared/_navbar.html.erb
Labels: waiting for review

#67 Basic html and css for show page
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/arts/_index.scss
  app/assets/stylesheets/arts/_show.scss
  app/views/arts/show.html.erb
Labels: waiting for review

#66 Art index
  app/assets/stylesheets/components/_button.scss
  app/assets/stylesheets/components/_cards.scss
  app/assets/stylesheets/pages/_index.scss
  app/controllers/arts_controller.rb
  app/views/arts/index.html.erb
  db/seeds.rb
Labels: waiting for review

#68 bookings controller and root creates
  app/controllers/bookings_controller.rb
  config/routes.rb
  test/controllers/bookings_controller_test.rb
Labels: waiting for review

#72 applied to category show
  app/assets/stylesheets/application.scss
  app/javascript/controllers/aos_controller.js
  app/javascript/controllers/index.js
  app/views/arts/index.html.erb
  app/views/categories/show.html.erb
  app/views/layouts/application.html.erb
  package.json
  yarn.lock
Labels: waiting for review

#79 Cleaned up of the Art index page and css
  app/assets/stylesheets/arts/_index.scss
  app/assets/stylesheets/components/_button.scss
  app/assets/stylesheets/components/_card.scss
  app/assets/stylesheets/components/_cards.scss
  app/assets/stylesheets/components/_container.scss
  app/assets/stylesheets/components/_index.scss
  app/assets/stylesheets/components/_listing.scss
  app/assets/stylesheets/pages/_index.scss
  app/views/arts/index.html.erb
  app/views/categories/show.html.erb
  app/views/shared/_listing.html.erb
Labels: waiting for review

#60 navbar dropdown
  app/assets/stylesheets/components/_navbar.scss
  app/javascript/controllers/dropdown_menu_controller.js
  app/javascript/controllers/index.js
  app/views/shared/_navbar.html.erb
  db/schema.rb
  yarn.lock
Labels: waiting for review

#73 created typed animation in the main page
  app/assets/stylesheets/pages/_home.scss
  app/javascript/controllers/index.js
  app/javascript/controllers/typed_controller.js
  app/views/pages/home.html.erb
  package.json
  yarn.lock
Labels: requires changes

#80 Moved navbar avatar to new avatar css component
  app/assets/stylesheets/components/_avatar.scss
  app/assets/stylesheets/components/_index.scss
  app/assets/stylesheets/components/_navbar.scss
Labels: waiting for review

#85 Users#show
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/components/_card.scss
  app/assets/stylesheets/devise/index.scss
  app/assets/stylesheets/devise/registrations/_edit.scss
  app/assets/stylesheets/users/index.scss
  app/assets/stylesheets/users/show.scss
  app/controllers/users_controller.rb
  app/views/devise/registrations/edit.html.erb
  app/views/users/show.html.erb
  config/routes.rb
  test/controllers/users_controller_test.rb
Labels: waiting for review

#90 Some fixes Camilla reccomended
  app/assets/stylesheets/pages/_home.scss
  app/views/arts/show.html.erb
  app/views/pages/home.html.erb
Labels: waiting for review

#93 Fixed a bug with the show booking form
  app/models/booking.rb
  app/views/arts/show.html.erb
Labels: waiting for review

#92 Users#security page
  app/assets/stylesheets/components/_card.scss
  app/assets/stylesheets/users/_index.scss
  app/assets/stylesheets/users/_security.scss
  app/assets/stylesheets/users/_show.scss
  app/assets/stylesheets/users/index.scss
  app/controllers/registrations_controller.rb
  app/controllers/users_controller.rb
  app/views/users/security.html.erb
  app/views/users/show.html.erb
  config/routes.rb
Labels: waiting for review

#89 Js patch
  app/assets/stylesheets/components/_navbar.scss
  app/assets/stylesheets/pages/_home.scss
  app/javascript/controllers/dropdown_menu_controller.js
  app/javascript/controllers/hello_controller.js
  app/javascript/controllers/index.js
  app/javascript/controllers/typed_controller.js
  app/views/pages/home.html.erb
  app/views/shared/_navbar.html.erb
Labels: waiting for review

#95 Carousel to art cards
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/components/_card.scss
  app/assets/stylesheets/components/_index.scss
  app/assets/stylesheets/components/_swiper.scss
  app/javascript/controllers/index.js
  app/views/shared/_listing.html.erb
  package.json
  yarn.lock
Labels: waiting for review

#97 Generated stimulus controller for price and blocked date fields
  app/assets/stylesheets/arts/_show.scss
  app/javascript/controllers/booking_form_price_controller.js
  app/javascript/controllers/index.js
  app/views/arts/show.html.erb
Labels: waiting for review

#100 Registrations form update
  app/views/devise/registrations/_form.html.erb
  app/views/devise/registrations/edit.html.erb
Labels: waiting for review

#87 review model
  app/models/art.rb
  app/models/review.rb
  app/models/user.rb
  db/migrate/20230223000336_create_reviews.rb
  db/schema.rb
  test/models/review_test.rb
Labels: waiting for review

#103 reviews controller
  app/controllers/reviews_controller.rb
  config/routes.rb
  test/controllers/reviews_controller_test.rb
Labels: waiting for review

#107 Review form
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/arts/_show.scss
  app/controllers/arts_controller.rb
  app/javascript/controllers/star_rating_controller.js
  app/views/arts/show.html.erb
  db/schema.rb
  package.json
  yarn.lock
Labels: waiting for review

#102 Added some missing link and tweaked the design a bit
  app/assets/stylesheets/components/_navbar.scss
  app/views/shared/_navbar.html.erb
Labels: waiting for review

#104 Address autocomplete for booking form
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/components/_address_autocomplete.scss
  app/assets/stylesheets/components/_button.scss
  app/assets/stylesheets/components/_index.scss
  app/javascript/controllers/address_autocomplete_controller.js
  app/javascript/controllers/index.js
  app/views/arts/show.html.erb
  config/initializers/devise.rb
  config/initializers/geocoder.rb
  package.json
  yarn.lock
Labels: waiting for review

#110 we made a search function:)
  Gemfile
  Gemfile.lock
  app/controllers/arts_controller.rb
  app/models/art.rb
  app/views/shared/_navbar.html.erb
Labels: requires changes

#109 Homepage
  app/assets/stylesheets/components/_card.scss
  app/assets/stylesheets/pages/_home.scss
  app/controllers/pages_controller.rb
  app/views/pages/home.html.erb
Labels: waiting for review

#105 Alert design layout
  app/assets/stylesheets/components/_alert.scss
  app/assets/stylesheets/components/_index.scss
  app/javascript/controllers/hide_devise_alert_controller.js
  app/javascript/controllers/index.js
  app/views/devise/sessions/new.html.erb
  app/views/devise/shared/_flashes.html.erb
  app/views/layouts/application.html.erb
Labels: requires changes

#111 User bookings page
  app/assets/stylesheets/components/_address_autocomplete.scss
  app/assets/stylesheets/components/_card.scss
  app/assets/stylesheets/components/_swiper.scss
  app/assets/stylesheets/users/_bookings.scss
  app/assets/stylesheets/users/_index.scss
  app/assets/stylesheets/users/_security.scss
  app/controllers/bookings_controller.rb
  app/controllers/users_controller.rb
  app/javascript/controllers/booking_form_price_controller.js
  app/javascript/controllers/index.js
  app/javascript/controllers/map_controller.js
  app/models/booking.rb
  app/views/arts/show.html.erb
  app/views/layouts/application.html.erb
  app/views/users/bookings.html.erb
  app/views/users/show.html.erb
  config/routes.rb
  db/migrate/20230227091551_add_price_and_coords_to_booking.rb
  db/schema.rb
Labels: waiting for review

#113 listing pages completed
  app/assets/stylesheets/users/_index.scss
  app/assets/stylesheets/users/_listings.scss
  app/assets/stylesheets/users/registrations/_edit.scss
  app/assets/stylesheets/users/registrations/_new.scss
  app/controllers/users_controller.rb
  app/views/users/bookings.html.erb
  app/views/users/listings.html.erb
  app/views/users/show.html.erb
  config/routes.rb
Labels: waiting for review
